### ISSUE TITLE
關於線上掃毒的結果

### ISSUE THREAD

**Issue by crack888wei** [mohuihui/antispy#1]
尊敬的zhenfei.mzf:

我非常喜歡您的這個作品但我透過線上掃毒卻發現與我本機電腦同樣問題會報毒，希望您能協助查
看是否正常謝謝。
這是非常棒的作品我很喜歡。

https://www.virustotal.com/gui/file/ef74dcc42dd4e5ac3226ca04ce8249e07a915c2a420649ef62d7f169e340296d/detection

**Comment by mohuihui** [comment]
大概看了一下，應該是殺毒引擎誤報，請放心使用哦，感謝！
